dist: trusty
sudo: required
language: node_js
cache:
  directories:
  - node_modules
  - $HOME/.npm
notifications:
  email: false
  slack: prodigyai:WkPfXfkgjsrAlIIisC6Ytm9b
node_js: 10
after_success:
- npx semantic-release
